version: '3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /media/mediastore/audioshelf/audiobooks:/audiobooks
      - /media/mediastore/audioshelf/podcasts:/podcasts
      - /media/mediastore/audioshelf/config:/config
      - /media/mediastore/audioshelf/metadata:/metadata
    restart: always
    environment:
      - TZ=America/New_York
      # OIDC Configuration
      - OIDC_ENABLED=true
      - OIDC_ISSUER_URL=https://audiobooks.syslogsolution.us
      - OIDC_CLIENT_ID='oidc-client-id'
      - OIDC_CLIENT_SECRET='oidc-client-secret-key'
      - OIDC_AUTO_REGISTER=true
      - OIDC_AUTO_LAUNCH=true
