services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest 
    init: true  
    restart: always 
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro   
    environment:
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_PORT=443
      - NEXTCLOUD_DOMAIN=nextcloud.syslogsolution.us
      - SKIP_DOMAIN_VALIDATION=true
    ports:
      - 127.0.0.1:11000:443
      - 8080:8080

volumes: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer    